//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS
    {
        public int CODBUS { get; set; }
        public string PLABUS { get; set; }
        public string ANIOBUS { get; set; }
        public Nullable<int> NROEJE { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODTIPSER { get; set; }
    }
}
