//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactenos
    {
        public int idcon { get; set; }
        public string nomcompcon { get; set; }
        public string dnicon { get; set; }
        public string corcon { get; set; }
        public string telcon { get; set; }
        public string celcon { get; set; }
        public string empcon { get; set; }
        public string comcon { get; set; }
    }
}
