//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJERO
    {
        public int CODPAS { get; set; }
        public string NOMPAS { get; set; }
        public string APEPPAS { get; set; }
        public string APEMPAS { get; set; }
        public string DIRPAS { get; set; }
        public string SEXPAS { get; set; }
        public string CELPAS { get; set; }
        public string TELPAS { get; set; }
        public string ESTREG { get; set; }
        public string ESTTRAN { get; set; }
        public Nullable<int> CODRES { get; set; }
        public string TIPDOC { get; set; }
        public string NUMDOC { get; set; }
    }
}
