//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        public int CODPER { get; set; }
        public string NOMPER { get; set; }
        public string APEPER { get; set; }
        public string DNIPER { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODUSU { get; set; }
    }
}
