//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_TARJETA
    {
        public int CODTARJETA { get; set; }
        public string NUMTAR { get; set; }
        public string CODTAR { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODTIPTAR { get; set; }
        public Nullable<int> CODCLI { get; set; }
    }
}
