//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_TIPO_TARJETA
    {
        public SRV_TIPO_TARJETA()
        {
            this.SRV_TARJETA = new HashSet<SRV_TARJETA>();
        }
    
        public int CODTIPTAR { get; set; }
        public string NOMTIPTAR { get; set; }
        public string ESTREG { get; set; }
        public string MEDPAG { get; set; }
    
        public virtual ICollection<SRV_TARJETA> SRV_TARJETA { get; set; }
    }
}
