//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_USUARIO
    {
        public int CODUSU { get; set; }
        public string CLAUSU { get; set; }
        public string ESTREG { get; set; }
        public string LOGUSU { get; set; }
        public Nullable<int> CODPER { get; set; }
    }
}
