//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_TARJETA
    {
        public SRV_TARJETA()
        {
            this.SRV_COMPRA = new HashSet<SRV_COMPRA>();
        }
    
        public int CODTARJETA { get; set; }
        public string NUMTAR { get; set; }
        public string CODTAR { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODTIPTAR { get; set; }
        public Nullable<int> CODCLI { get; set; }
        public string CODVER { get; set; }
        public string NOMTIT { get; set; }
        public string APETIT { get; set; }
        public string FECEXP { get; set; }
    
        public virtual ICollection<SRV_COMPRA> SRV_COMPRA { get; set; }
        public virtual SRV_TIPO_TARJETA SRV_TIPO_TARJETA { get; set; }
    }
}
