//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_RESERVA
    {
        public SRV_RESERVA()
        {
            this.SRV_COMPRA = new HashSet<SRV_COMPRA>();
        }
    
        public int CODRES { get; set; }
        public Nullable<System.DateTime> FECRES { get; set; }
        public string ESTREG { get; set; }
        public string ESTTRAN { get; set; }
        public Nullable<int> CODCLI { get; set; }
        public Nullable<int> CODPRO { get; set; }
        public Nullable<int> CODPRODES { get; set; }
    
        public virtual ICollection<SRV_COMPRA> SRV_COMPRA { get; set; }
    }
}
