//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_VW_RESERVAS
    {
        public int CODRES { get; set; }
        public string FECRES { get; set; }
        public string FECSALPRO { get; set; }
        public string HORSALPRO { get; set; }
        public string ORITAR { get; set; }
        public string DESTAR { get; set; }
        public string TIPVIA { get; set; }
        public string CORCLI { get; set; }
        public string ESTTRAN { get; set; }
    }
}
