//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_PROGRAMACION
    {
        public int CODPRO { get; set; }
        public Nullable<System.DateTime> FECSALPRO { get; set; }
        public string HORSALPRO { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODBUS { get; set; }
        public Nullable<int> CODTAR { get; set; }
        public Nullable<int> CODPROM { get; set; }
    }
}
